// apps/web/src/components/Theme/ThemeDesigner/sections/GlobalSection.tsx
import type { GlobalSectionProps } from "../types";
import { ColorSelector } from "../../ColorSelector";
import {
  fontFamilyOptions,
  fontSizeOptions,
  lineHeightOptions,
  primaryColorOptions,
  boldStyleOptions,
} from "../../../../config/styleOptions";

export function GlobalSection({
  variables,
  updateVariable,
  handlePrimaryColorChange,
}: GlobalSectionProps) {
  return (
    <div className="designer-section">
      <div className="designer-field">
        <label>字体</label>
        <div className="designer-options">
          {fontFamilyOptions.map((opt) => (
            <button
              key={opt.value}
              className={`option-btn ${variables.fontFamily === opt.value ? "active" : ""}`}
              onClick={() => updateVariable("fontFamily", opt.value)}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </div>

      <div className="designer-field">
        <label>正文字号</label>
        <div className="designer-options">
          {fontSizeOptions.map((opt) => (
            <button
              key={opt.value}
              className={`option-btn ${variables.fontSize === opt.value ? "active" : ""}`}
              onClick={() => updateVariable("fontSize", opt.value)}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </div>

      <div className="designer-field">
        <label>行高</label>
        <div className="designer-options">
          {lineHeightOptions.map((opt) => (
            <button
              key={opt.value}
              className={`option-btn ${variables.lineHeight === opt.value ? "active" : ""}`}
              onClick={() => updateVariable("lineHeight", opt.value)}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </div>

      <div className="designer-field">
        <label>页面边距: {variables.pagePadding}px</label>
        <input
          type="range"
          className="designer-slider"
          min={0}
          max={48}
          step={1}
          value={variables.pagePadding || 0}
          onChange={(e) =>
            updateVariable("pagePadding", Number(e.target.value))
          }
        />
      </div>

      <div className="designer-field">
        <label>正文颜色</label>
        <ColorSelector
          value={variables.paragraphColor}
          presets={[
            { label: "深灰 (推荐)", value: "#333333" },
            { label: "纯黑", value: "#000000" },
            { label: "灰色", value: "#666666" },
          ]}
          onChange={(color) => updateVariable("paragraphColor", color)}
        />
      </div>

      <div className="designer-field">
        <label>主题色</label>
        <ColorSelector
          value={variables.primaryColor}
          presets={primaryColorOptions}
          onChange={handlePrimaryColorChange}
        />
      </div>

      <div className="designer-field">
        <label>加粗样式</label>
        <div className="designer-options">
          {boldStyleOptions.map((opt) => (
            <button
              key={opt.id}
              className={`option-btn ${variables.strongStyle === opt.id ? "active" : ""}`}
              onClick={() => updateVariable("strongStyle", opt.id)}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// apps/web/src/components/Theme/ThemeDesigner/sections/GlobalSection.vue
<script setup lang="ts">
import { computed } from "vue";
import ColorSelector from "../ColorSelector.vue";
import {
  fontFamilyOptions,
  fontSizeOptions,
  lineHeightOptions,
  primaryColorOptions,
  boldStyleOptions,
} from "@/config/styleOptions";
import type { DesignerVariables } from "../types";

const props = defineProps<{
  variables: DesignerVariables;
}>();

const emit = defineEmits<{
  (e: "change", updates: Partial<DesignerVariables>): void;
  (e: "primary-color-change", color: string): void;
}>();

const updateVariable = <K extends keyof DesignerVariables>(
  key: K,
  value: DesignerVariables[K]
) => {
  emit("change", { [key]: value });
};

const handlePrimaryColorChange = (color: string) => {
  emit("primary-color-change", color);
};
</script>

<template>
  <div class="designer-section">
    <div class="designer-field">
      <label>字体</label>
      <div class="designer-options">
        <button
          v-for="opt in fontFamilyOptions"
          :key="opt.value"
          class="option-btn"
          :class="{ active: variables.fontFamily === opt.value }"
          @click="updateVariable('fontFamily', opt.value)"
        >
          {{ opt.label }}
        </button>
      </div>
    </div>

    <div class="designer-field">
      <label>正文字号</label>
      <div class="designer-options">
        <button
          v-for="opt in fontSizeOptions"
          :key="opt.value"
          class="option-btn"
          :class="{ active: variables.fontSize === opt.value }"
          @click="updateVariable('fontSize', opt.value)"
        >
          {{ opt.label }}
        </button>
      </div>
    </div>

    <div class="designer-field">
      <label>行高</label>
      <div class="designer-options">
        <button
          v-for="opt in lineHeightOptions"
          :key="opt.value"
          class="option-btn"
          :class="{ active: variables.lineHeight === opt.value }"
          @click="updateVariable('lineHeight', opt.value)"
        >
          {{ opt.label }}
        </button>
      </div>
    </div>

    <div class="designer-field">
      <label>页面边距: {{ variables.pagePadding }}px</label>
      <input
        type="range"
        class="designer-slider"
        :min="0"
        :max="48"
        :step="1"
        :value="variables.pagePadding || 0"
        @input="updateVariable('pagePadding', Number(($event.target as HTMLInputElement).value))"
      />
    </div>

    <div class="designer-field">
      <label>正文颜色</label>
      <ColorSelector
        :value="variables.paragraphColor"
        :presets="[
          { label: '深灰 (推荐)', value: '#333333' },
          { label: '纯黑', value: '#000000' },
          { label: '灰色', value: '#666666' },
        ]"
        @change="updateVariable('paragraphColor', $event)"
      />
    </div>

    <div class="designer-field">
      <label>主题色</label>
      <ColorSelector
        :value="variables.primaryColor"
        :presets="primaryColorOptions"
        @change="handlePrimaryColorChange"
      />
    </div>

    <div class="designer-field">
      <label>加粗样式</label>
      <div class="designer-options">
        <button
          v-for="opt in boldStyleOptions"
          :key="opt.id"
          class="option-btn"
          :class="{ active: variables.strongStyle === opt.id }"
          @click="updateVariable('strongStyle', opt.id)"
        >
          {{ opt.label }}
        </button>
      </div>
    </div>
  </div>
</template>
