// apps/web/src/components/Sidebar/FileSidebar.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { useFileSystem } from '../../composables/useFileSystem'
import { useThemeStore } from '../../stores/theme'
import { useFileStore } from '../../stores/file'
import { Search, Plus, Trash2, FolderOpen, Edit2, MoreHorizontal, Copy } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import type { FileItem } from '../../store/fileTypes'
import './FileSidebar.css'

const PAGE_SIZE = 50

const { openFile, createFile, renameFile, deleteFile, selectWorkspace, workspacePath } = useFileSystem()
const themeStore = useThemeStore()
const fileStore = useFileStore()

const currentThemeName = computed(() => themeStore.themeName)
const filter = ref('')
const renamingPath = ref<string | null>(null)
const renameValue = ref('')
const visibleCount = ref(PAGE_SIZE)
const loadMoreRef = ref<HTMLDivElement | null>(null)

// 右键菜单状态
const menuOpen = ref(false)
const menuPos = ref({ x: 0, y: 0 })
const menuTarget = ref<FileItem | null>(null)
const deleteTarget = ref<FileItem | null>(null)
const deleting = ref(false)

const filteredFiles = computed(() => {
  const fileList = fileStore.files
  if (!filter.value) return fileList
  return fileList.filter(f => f.name.toLowerCase().includes(filter.value.toLowerCase()))
})

const visibleFiles = computed(() => filteredFiles.value.slice(0, visibleCount.value))
const hasMore = computed(() => visibleCount.value < filteredFiles.value.length)

function loadMore() {
  if (hasMore.value) {
    visibleCount.value = Math.min(visibleCount.value + PAGE_SIZE, filteredFiles.value.length)
  }
}

// Intersection Observer
let observer: IntersectionObserver | null = null

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0].isIntersecting && hasMore.value) {
        loadMore()
      }
    },
    { threshold: 0.1 }
  )

  if (loadMoreRef.value) {
    observer.observe(loadMoreRef.value)
  }
})

onUnmounted(() => {
  observer?.disconnect()
})

watch(filter, () => {
  visibleCount.value = PAGE_SIZE
})

function handleContextMenu(e: MouseEvent, file: FileItem) {
  e.preventDefault()
  e.stopPropagation()
  menuTarget.value = file
  menuPos.value = { x: e.clientX, y: e.clientY }
  menuOpen.value = true
}

function closeMenu() {
  menuOpen.value = false
  menuTarget.value = null
}

function startRename(file: FileItem) {
  renamingPath.value = file.path
  renameValue.value = file.name.replace('.md', '')
  closeMenu()
}

async function copyTitle(file: FileItem) {
  try {
    const title = file.name.replace('.md', '')
    await navigator.clipboard.writeText(title)
    toast.success('标题已复制')
  } catch {
    toast.error('复制失败')
  }
  closeMenu()
}

async function submitRename() {
  if (renamingPath.value && renameValue.value) {
    const file = fileStore.files.find(f => f.path === renamingPath.value)
    if (file) {
      await renameFile(file, renameValue.value)
    }
  }
  renamingPath.value = null
}

async function confirmDelete() {
  if (!deleteTarget.value) return
  deleting.value = true
  try {
    await deleteFile(deleteTarget.value)
  } finally {
    deleting.value = false
    deleteTarget.value = null
    closeMenu()
  }
}
</script>

<template>
  <aside class="file-sidebar">
    <div class="fs-header">
      <div
        class="fs-workspace-info"
        :title="workspacePath || '选择工作区'"
        @click="selectWorkspace"
      >
        <FolderOpen :size="14" />
        <span>{{ workspacePath ? workspacePath.split('/').pop() : '选择工作区' }}</span>
      </div>
      <div class="fs-actions">
        <button
          class="fs-btn-secondary fs-btn-icon-only"
          title="新建文章"
          @click="createFile"
        >
          <Plus :size="16" />
        </button>
      </div>
    </div>

    <div class="fs-search">
      <div class="fs-search-wrapper">
        <Search
          :size="14"
          class="fs-search-icon"
        />
        <input
          v-model="filter"
          type="text"
          placeholder="搜索文件..."
        />
      </div>
    </div>

    <div class="fs-body">
      <div class="fs-list">
        <div
          v-for="file in visibleFiles"
          :key="file.path"
          :class="['fs-item', { active: fileStore.currentFile?.path === file.path }]"
          @click="openFile(file)"
          @contextmenu="handleContextMenu($event, file)"
        >
          <div class="fs-item-main">
            <div class="fs-title-block">
              <span class="fs-time">{{ new Date(file.updatedAt).toLocaleString() }}</span>
              <div
                v-if="renamingPath === file.path"
                class="fs-rename"
                @click.stop
              >
                <input
                  v-model="renameValue"
                  autofocus
                  @keydown.enter="submitRename"
                  @keydown.escape="renamingPath = null"
                />
                <button @click="submitRename">
                  确认
                </button>
                <button @click="renamingPath = null">
                  取消
                </button>
              </div>
              <template v-else>
                <span
                  class="fs-title"
                  :title="file.name"
                >{{ file.name }}</span>
                <span class="fs-theme-info">
                  {{ fileStore.currentFile?.path === file.path ? currentThemeName : (file.themeName || '默认主题') }}
                </span>
              </template>
            </div>
            <button
              class="fs-action-trigger"
              @click.stop="handleContextMenu($event, file)"
            >
              <MoreHorizontal :size="16" />
            </button>
          </div>
        </div>

        <div
          v-if="hasMore"
          ref="loadMoreRef"
          class="fs-load-more"
        >
          <span>加载更多...</span>
        </div>
        <div
          v-if="filteredFiles.length === 0"
          class="fs-empty"
        >
          暂无文件
        </div>
      </div>
    </div>

    <!-- Context Menu -->
    <Teleport to="body">
      <div
        v-if="menuOpen"
        class="fs-context-menu-overlay"
        @click="closeMenu"
      >
        <div
          class="fs-context-menu"
          :style="{ top: menuPos.y + 'px', left: menuPos.x + 'px' }"
        >
          <button @click="copyTitle(menuTarget!)">
            <Copy :size="14" /> 复制标题
          </button>
          <button @click="startRename(menuTarget!)">
            <Edit2 :size="14" /> 重命名
          </button>
          <button
            class="danger"
            @click="deleteTarget = menuTarget; closeMenu()"
          >
            <Trash2 :size="14" /> 删除
          </button>
        </div>
      </div>
    </Teleport>

    <!-- Delete Confirm Modal -->
    <Teleport to="body">
      <div
        v-if="deleteTarget"
        class="history-confirm-backdrop"
        @click="!deleting && (deleteTarget = null)"
      >
        <div
          class="history-confirm-modal"
          @click.stop
        >
          <h4>删除文件</h4>
          <p>确定要删除"{{ deleteTarget.name }}"吗？此操作不可撤销。</p>
          <div class="history-confirm-actions">
            <button
              class="btn-secondary"
              :disabled="deleting"
              @click="deleteTarget = null"
            >
              取消
            </button>
            <button
              class="btn-danger"
              :disabled="deleting"
              @click="confirmDelete"
            >
              {{ deleting ? '删除中...' : '确认删除' }}
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </aside>
</template>

// apps/web/src/components/Sidebar/FileSidebar.tsx
import { useState, useMemo, useRef, useEffect, useCallback } from "react";
import { useFileSystem } from "../../hooks/useFileSystem";
import { useThemeStore } from "../../store/themeStore";
import {
  Search,
  Plus,
  Trash2,
  FolderOpen,
  Edit2,
  MoreHorizontal,
  Copy,
} from "lucide-react";
import { createPortal } from "react-dom";
import toast from "react-hot-toast";
import "./FileSidebar.css";

import type { FileItem } from "../../store/fileTypes";

// 每次加载的文件数量
const PAGE_SIZE = 50;

export function FileSidebar() {
  const {
    files,
    currentFile,
    openFile,
    createFile,
    renameFile,
    deleteFile,
    selectWorkspace,
    workspacePath,
  } = useFileSystem();
  const currentThemeName = useThemeStore((state) => state.themeName);
  const [filter, setFilter] = useState("");
  const [renamingPath, setRenamingPath] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState("");

  // 无限滚动状态
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
  const loadMoreRef = useRef<HTMLDivElement>(null);

  // 右键菜单状态
  const [menuOpen, setMenuOpen] = useState(false);
  const [menuPos, setMenuPos] = useState({ x: 0, y: 0 });
  const [menuTarget, setMenuTarget] = useState<FileItem | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<FileItem | null>(null);
  const [deleting, setDeleting] = useState(false);

  const filteredFiles = useMemo(() => {
    if (!filter) return files;
    return files.filter((f) =>
      f.name.toLowerCase().includes(filter.toLowerCase()),
    );
  }, [files, filter]);

  // 当前可见的文件列表
  const visibleFiles = useMemo(() => {
    return filteredFiles.slice(0, visibleCount);
  }, [filteredFiles, visibleCount]);

  // 是否还有更多文件可加载
  const hasMore = visibleCount < filteredFiles.length;

  // 加载更多文件
  const loadMore = useCallback(() => {
    if (hasMore) {
      setVisibleCount((prev) =>
        Math.min(prev + PAGE_SIZE, filteredFiles.length),
      );
    }
  }, [hasMore, filteredFiles.length]);

  // 使用 Intersection Observer 检测滚动到底部
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore) {
          loadMore();
        }
      },
      { threshold: 0.1 },
    );

    if (loadMoreRef.current) {
      observer.observe(loadMoreRef.current);
    }

    return () => observer.disconnect();
  }, [hasMore, loadMore]);

  // 搜索条件变化时重置可见数量
  useEffect(() => {
    setVisibleCount(PAGE_SIZE);
  }, [filter]);

  const handleContextMenu = (e: React.MouseEvent, file: FileItem) => {
    e.preventDefault();
    e.stopPropagation();
    setMenuTarget(file);
    setMenuPos({ x: e.clientX, y: e.clientY });
    setMenuOpen(true);
  };

  const closeMenu = () => {
    setMenuOpen(false);
    setMenuTarget(null);
  };

  const startRename = (file: FileItem) => {
    setRenamingPath(file.path);
    setRenameValue(file.name.replace(".md", ""));
    closeMenu();
  };

  const copyTitle = async (file: FileItem) => {
    try {
      const title = file.name.replace(".md", "");
      await navigator.clipboard.writeText(title);
      toast.success("标题已复制");
    } catch {
      toast.error("复制失败");
    }
    closeMenu();
  };

  const submitRename = async () => {
    if (renamingPath && renameValue) {
      const file = files.find((f) => f.path === renamingPath);
      if (file) {
        await renameFile(file, renameValue);
      }
    }
    setRenamingPath(null);
  };

  return (
    <aside className="file-sidebar">
      <div className="fs-header">
        <div
          className="fs-workspace-info"
          onClick={selectWorkspace}
          title={workspacePath || "选择工作区"}
        >
          <FolderOpen size={14} />
          <span>
            {workspacePath ? workspacePath.split("/").pop() : "选择工作区"}
          </span>
        </div>
        <div className="fs-actions">
          <button
            className="fs-btn-secondary fs-btn-icon-only"
            onClick={createFile}
            title="新建文章"
          >
            <Plus size={16} />
          </button>
        </div>
      </div>

      <div className="fs-search">
        <div className="fs-search-wrapper">
          <Search size={14} className="fs-search-icon" />
          <input
            type="text"
            placeholder="搜索文件..."
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
          />
        </div>
      </div>

      <div className="fs-body">
        <div className="fs-list">
          {visibleFiles.map((file) => (
            <div
              key={file.path}
              className={`fs-item ${currentFile?.path === file.path ? "active" : ""}`}
              onClick={() => openFile(file)}
              onContextMenu={(e) => handleContextMenu(e, file)}
            >
              <div className="fs-item-main">
                <div className="fs-title-block">
                  <span className="fs-time">
                    {new Date(file.updatedAt).toLocaleString()}
                  </span>
                  {renamingPath === file.path ? (
                    <div
                      className="fs-rename"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <input
                        value={renameValue}
                        onChange={(e) => setRenameValue(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter") submitRename();
                          if (e.key === "Escape") setRenamingPath(null);
                        }}
                        autoFocus
                      />
                      <button onClick={() => submitRename()}>确认</button>
                      <button onClick={() => setRenamingPath(null)}>
                        取消
                      </button>
                    </div>
                  ) : (
                    <span className="fs-title" title={file.name}>
                      {file.name}
                    </span>
                  )}
                  {renamingPath !== file.path && (
                    <span className="fs-theme-info">
                      {currentFile?.path === file.path
                        ? currentThemeName
                        : file.themeName || "默认主题"}
                    </span>
                  )}
                </div>
                <button
                  className="fs-action-trigger"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleContextMenu(e, file);
                  }}
                >
                  <MoreHorizontal size={16} />
                </button>
              </div>
            </div>
          ))}
          {/* 无限滚动触发器 */}
          {hasMore && (
            <div ref={loadMoreRef} className="fs-load-more">
              <span>加载更多...</span>
            </div>
          )}
          {filteredFiles.length === 0 && (
            <div className="fs-empty">暂无文件</div>
          )}
        </div>
      </div>

      {/* Context Menu Portal */}
      {menuOpen &&
        createPortal(
          <div className="fs-context-menu-overlay" onClick={closeMenu}>
            <div
              className="fs-context-menu"
              style={{ top: menuPos.y, left: menuPos.x }}
            >
              <button onClick={() => menuTarget && copyTitle(menuTarget)}>
                <Copy size={14} /> 复制标题
              </button>
              <button onClick={() => menuTarget && startRename(menuTarget)}>
                <Edit2 size={14} /> 重命名
              </button>
              <button
                className="danger"
                onClick={() => {
                  setDeleteTarget(menuTarget);
                  closeMenu();
                }}
              >
                <Trash2 size={14} /> 删除
              </button>
            </div>
          </div>,
          document.body,
        )}
      {deleteTarget &&
        createPortal(
          <div
            className="fs-confirm-backdrop"
            onClick={() => !deleting && setDeleteTarget(null)}
          >
            <div
              className="fs-confirm-modal"
              onClick={(e) => e.stopPropagation()}
            >
              <h4>删除文件</h4>
              <p>确定要删除“{deleteTarget.name}”吗？此操作不可撤销。</p>
              <div className="fs-confirm-actions">
                <button
                  className="btn-secondary"
                  onClick={() => setDeleteTarget(null)}
                  disabled={deleting}
                >
                  取消
                </button>
                <button
                  className="btn-danger"
                  onClick={async () => {
                    setDeleting(true);
                    try {
                      await deleteFile(deleteTarget);
                    } finally {
                      setDeleting(false);
                      setDeleteTarget(null);
                      closeMenu();
                    }
                  }}
                  disabled={deleting}
                >
                  {deleting ? "删除中..." : "确认删除"}
                </button>
              </div>
            </div>
          </div>,
          document.body,
        )}
    </aside>
  );
}
